# Generated by Django 5.0.3 on 2024-03-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoTramites',
            fields=[
                ('id_negocio', models.CharField(max_length=255)),
                ('tipo_tramite', models.CharField(max_length=255)),
                ('numero_radicacion', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=255)),
                ('zona', models.CharField(max_length=255)),
                ('numero_predial', models.CharField(max_length=255)),
                ('ultima_tarea_proceso', models.CharField(max_length=255)),
                ('fecha_inicio_ultima_tarea', models.DateField()),
                ('fecha_fin_ultima_tarea', models.DateField()),
                ('ultimo_control_calidad', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('fecha_inicio_tarea', models.DateField()),
                ('departamento', models.CharField(max_length=255)),
                ('municipio_codigo', models.CharField(max_length=255)),
                ('territorial_ldap', models.CharField(max_length=255)),
                ('tipo_est_organizacional', models.CharField(max_length=255)),
            ],
        ),
    ]
