# Generated by Django 5.0.3 on 2024-03-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seguimientotramites'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosMaestros',
            fields=[
                ('territorial', models.CharField(max_length=255)),
                ('id_negocio', models.CharField(max_length=255)),
                ('numero_solicitud', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('zona', models.CharField(max_length=255)),
                ('numero_radicacion', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('numero_predial', models.CharField(max_length=255)),
                ('tipo_tramite', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(max_length=255)),
                ('estado_tramite', models.CharField(max_length=255)),
                ('estado_proceso', models.CharField(max_length=255)),
                ('inicio_proceso', models.DateField()),
                ('fin_proceso', models.DateField()),
                ('tarea', models.CharField(max_length=255)),
                ('estado_tarea', models.CharField(max_length=255)),
                ('fecha_inicio_tarea', models.DateField()),
                ('fecha_fin_tarea', models.DateField()),
                ('dias_habiles', models.IntegerField()),
                ('funcionario_radicador', models.CharField(max_length=255)),
                ('usuario_propietario', models.CharField(max_length=255)),
                ('numero_resolucion', models.CharField(max_length=255)),
                ('fecha_resolucion', models.DateField()),
                ('radicacion_masivo', models.CharField(max_length=255)),
                ('folio_matricula', models.CharField(max_length=255)),
            ],
        ),
    ]
