# Generated by Django 5.0.3 on 2024-03-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datosmaestros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmaestros',
            name='dias_habiles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosmaestros',
            name='fecha_fin_tarea',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datosmaestros',
            name='fecha_inicio_tarea',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datosmaestros',
            name='fecha_resolucion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datosmaestros',
            name='fin_proceso',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datosmaestros',
            name='inicio_proceso',
            field=models.CharField(max_length=255),
        ),
    ]
