# Generated by Django 5.0.3 on 2024-03-28 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_datosmaestros_dias_habiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDatosMaestros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(default='default.csv', upload_to='archivos_csv/')),
                ('fecha_subida', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='SeguimientoTramites',
        ),
    ]
