# Generated by Django 5.0.3 on 2024-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_filedatosmaestros_fecha_subida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedatosmaestros',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 12:53:15', editable=False),
        ),
    ]
