# Generated by Django 5.0.3 on 2024-03-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_filedatosmaestros_fecha_subida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientoejecutoresa',
            name='fecha_inicio_tarea_ejecucion',
        ),
        migrations.RemoveField(
            model_name='seguimientoejecutoresb',
            name='fecha_inicio_tarea_ejecucion',
        ),
        migrations.AlterField(
            model_name='filedatosmaestros',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 14:37:58', editable=False),
        ),
        migrations.AlterField(
            model_name='filepdfgdb',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 14:37:58', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresa',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 14:37:58', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresb',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 14:37:58', editable=False),
        ),
        migrations.AlterField(
            model_name='seguimientoejecutoresa',
            name='fecha_fin_tarea_ejecucion',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientoejecutoresa',
            name='fecha_fin_ultima_tarea',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientoejecutoresa',
            name='fecha_inicio_ultima_tarea',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientoejecutoresb',
            name='fecha_fin_tarea_ejecucion',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientoejecutoresb',
            name='fecha_fin_ultima_tarea',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientoejecutoresb',
            name='fecha_inicio_ultima_tarea',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
