# Generated by Django 5.0.3 on 2024-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_seguimientoejecutoresa_fecha_inicio_tarea_ejecucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedatosmaestros',
            name='archivo',
            field=models.FileField(default='default.csv', upload_to='files/archivos_csv/'),
        ),
        migrations.AlterField(
            model_name='filedatosmaestros',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 14:59:32', editable=False),
        ),
        migrations.AlterField(
            model_name='filepdfgdb',
            name='archivo',
            field=models.FileField(default='default.pdf', upload_to='files/archivos_pdf/'),
        ),
        migrations.AlterField(
            model_name='filepdfgdb',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 14:59:32', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresa',
            name='archivo',
            field=models.FileField(default='default_a.csv', upload_to='files/seguimiento_ejecutor_a_csv/'),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresa',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 14:59:32', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresb',
            name='archivo',
            field=models.FileField(default='default_b.csv', upload_to='files/seguimiento_ejecutor_b_csv/'),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresb',
            name='fecha_subida',
            field=models.TextField(default='2024-03-28 14:59:32', editable=False),
        ),
    ]
