# Generated by Django 5.0.3 on 2024-03-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_filedatosmaestros_fecha_subida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimientoejecutoresa',
            old_name='fecha_fin_tarea_ejecucion',
            new_name='fecha_fin_tarea_de_ejecucion',
        ),
        migrations.RenameField(
            model_name='seguimientoejecutoresa',
            old_name='ultima_tarea_proceso',
            new_name='ultima_tarea_del_proceso',
        ),
        migrations.RenameField(
            model_name='seguimientoejecutoresb',
            old_name='fecha_fin_tarea_ejecucion',
            new_name='fecha_fin_tarea_de_ejecucion',
        ),
        migrations.RenameField(
            model_name='seguimientoejecutoresb',
            old_name='ultima_tarea_proceso',
            new_name='ultima_tarea_del_proceso',
        ),
        migrations.AddField(
            model_name='seguimientoejecutoresa',
            name='fecha_inicio_tarea_de_ejecucion',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seguimientoejecutoresb',
            name='fecha_inicio_tarea_de_ejecucion',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filedatosmaestros',
            name='fecha_subida',
            field=models.TextField(default='2024-03-29 13:09:07', editable=False),
        ),
        migrations.AlterField(
            model_name='filepdfgdb',
            name='fecha_subida',
            field=models.TextField(default='2024-03-29 13:09:07', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresa',
            name='fecha_subida',
            field=models.TextField(default='2024-03-29 13:09:07', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresb',
            name='fecha_subida',
            field=models.TextField(default='2024-03-29 13:09:07', editable=False),
        ),
    ]
