# Generated by Django 5.0.3 on 2024-03-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_fecha_fin_tarea_ejecucion_seguimientoejecutoresa_fecha_fin_tarea_de_ejecucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('numero_solicitud', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('numero_radicacion', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('numero_predial', models.CharField(max_length=255)),
                ('tipo_tramite', models.CharField(max_length=255)),
                ('tarea', models.CharField(max_length=255)),
                ('estado_tarea', models.CharField(max_length=255)),
                ('fecha_inicio_tarea', models.DateField(blank=True, null=True)),
                ('usuario_propietario', models.CharField(max_length=255)),
                ('numero_resolucion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='filedatosmaestros',
            name='fecha_subida',
            field=models.TextField(default='2024-03-29 23:43:54', editable=False),
        ),
        migrations.AlterField(
            model_name='filepdfgdb',
            name='fecha_subida',
            field=models.TextField(default='2024-03-29 23:43:54', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresa',
            name='archivo',
            field=models.FileField(default='default.csv', upload_to='files/seguimiento_ejecutor_a_csv/'),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresa',
            name='fecha_subida',
            field=models.TextField(default='2024-03-29 23:43:54', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresb',
            name='archivo',
            field=models.FileField(default='default.csv', upload_to='files/seguimiento_ejecutor_b_csv/'),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresb',
            name='fecha_subida',
            field=models.TextField(default='2024-03-29 23:43:54', editable=False),
        ),
    ]
