# Generated by Django 5.0.3 on 2024-04-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_filedatosmaestros_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedatosmaestros',
            name='fecha_subida',
            field=models.TextField(default='2024-04-02 16:14:22', editable=False),
        ),
        migrations.AlterField(
            model_name='filepdfgdb',
            name='fecha_subida',
            field=models.TextField(default='2024-04-02 16:14:22', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresa',
            name='fecha_subida',
            field=models.TextField(default='2024-04-02 16:14:22', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresb',
            name='fecha_subida',
            field=models.TextField(default='2024-04-02 16:14:22', editable=False),
        ),
    ]
