# Generated by Django 5.0.4 on 2024-04-08 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_filedatosmaestros_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosmaestros',
            name='dias_habiles',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filedatosmaestros',
            name='fecha_subida',
            field=models.TextField(default='2024-04-07 23:35:41', editable=False),
        ),
        migrations.AlterField(
            model_name='filepdfgdb',
            name='fecha_subida',
            field=models.TextField(default='2024-04-07 23:35:41', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresa',
            name='fecha_subida',
            field=models.TextField(default='2024-04-07 23:35:41', editable=False),
        ),
        migrations.AlterField(
            model_name='fileseguimientoejecutoresb',
            name='fecha_subida',
            field=models.TextField(default='2024-04-07 23:35:41', editable=False),
        ),
    ]
